language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

cache: pip

# command to install dependencies
install:
  - echo starting
  - set
  - pip install -r requirements.txt
  - pip install -q pytest-cov==2.4.0
  - pip install -q python-coveralls
  - pip install -q codacy-coverage

script:
  - pytest --cov=sovon_cms

notifications:
  recipients:
    - lixf@sovon.net

  on_success: change
  on_failure: change

after_success:
  - coveralls
  - coverage xml
  - python-codacy-coverage -r coverage.xml